### ISSUE TITLE
routing not working in netlify deploy

### ISSUE THREAD

**Issue by jaionearnaez** [jaionearnaez/this-film-finder#7]
- [ ] try adding a netlify.toml file with
```toml
[build]
  publish = "dist/apps/this-film-finder"
  command = "npm run build:this-film-finder"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
```
